---
title: Bird watch website 3.0
hero_image: images/banner.png
description: Add nice layouts and cool effects to your website!
theme: navy
listed: false
copyedit: true
curriculum: ''
interests: ''
technologies: html-css-javascript
site_areas: coderdojo, projects
hardware: ''
software: html-css-javascript
version: 3.1.0
last_tested: '2018-04-17'
steps:
  - title: You will make
  - title: Add a featured image caption
  - title: Add a preview card
    completion:
      - engaged
  - title: Style the preview card
  - title: Link and arrange your cards
  - title: Make the menu responsive
  - title: Add side notes to the birds page
  - title: Build a page grid
    completion:
      - internal
  - title: Create a photo collage
  - title: Add hover and lightbox effects
    completion:
      - external
  - title: Challenge
    challenge: true
