---
title: Bird watch website 3.0
hero_image: images/banner.png
description: Add nice layouts and cool effects to your website!
theme: navy
listed: false
copyedit: true
curriculum: ''
interests: ''
technologies: html-css-javascript
site_areas: coderdojo, projects
hardware: ''
software: html-css-javascript
version: 3.1.0
last_tested: '2018-04-17'
landing: true
steps:
  - title: Add a preview card
  - title: Style the preview card
    completion:
      - engaged
  - title: Make your cards clickable
  - title: Add more bird cards
  - title: Centre the cards
  - title: Arrange the cards in a row
  - title: Improve the card hover effect
  - title: Add a featured image caption
  - title: Make the menu responsive
  - title: Add side notes to the birds page
  - title: Build a page grid
  - title: Style the side notes
    completion:
      - internal
  - title: Challenge: Create a photo collage
    completion:
      - external
  - title: Challenge: Style the photo collage
    challenge: true
